// <auto-generated />
using System;
using MangaAccessService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaAccessService.Migrations
{
    [DbContext(typeof(MangaNNovelAuthDBContext))]
    [Migration("20221230202035_NovelXmanga")]
    partial class NovelXmanga
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ChapterModelGroupScanlatingModel", b =>
                {
                    b.Property<int>("GroupScanlatingModelsGroupScanlatingID")
                        .HasColumnType("int");

                    b.Property<int>("chapterModelschapterID")
                        .HasColumnType("int");

                    b.HasKey("GroupScanlatingModelsGroupScanlatingID", "chapterModelschapterID");

                    b.HasIndex("chapterModelschapterID");

                    b.ToTable("ChapterModelGroupScanlatingModel");
                });

            modelBuilder.Entity("GenresModelMangaModel", b =>
                {
                    b.Property<int>("GenresModelsGenresId")
                        .HasColumnType("int");

                    b.Property<int>("MangaModelsMangaID")
                        .HasColumnType("int");

                    b.HasKey("GenresModelsGenresId", "MangaModelsMangaID");

                    b.HasIndex("MangaModelsMangaID");

                    b.ToTable("GenresModelMangaModel");
                });

            modelBuilder.Entity("GroupScanlatingModelMasterModel", b =>
                {
                    b.Property<int>("GroupScanlatingID")
                        .HasColumnType("int");

                    b.Property<int>("MasterModelsMasterID")
                        .HasColumnType("int");

                    b.HasKey("GroupScanlatingID", "MasterModelsMasterID");

                    b.HasIndex("MasterModelsMasterID");

                    b.ToTable("GroupScanlatingModelMasterModel");
                });

            modelBuilder.Entity("GroupScanlatingModelUserModel", b =>
                {
                    b.Property<int>("GroupScanlatingID")
                        .HasColumnType("int");

                    b.Property<string>("userModelsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GroupScanlatingID", "userModelsId");

                    b.HasIndex("userModelsId");

                    b.ToTable("GroupScanlatingModelUserModel");
                });

            modelBuilder.Entity("MangaModelMangaModel", b =>
                {
                    b.Property<int>("RecommendedMangaModelsMangaID")
                        .HasColumnType("int");

                    b.Property<int>("relatedSeriesMangaID")
                        .HasColumnType("int");

                    b.HasKey("RecommendedMangaModelsMangaID", "relatedSeriesMangaID");

                    b.HasIndex("relatedSeriesMangaID");

                    b.ToTable("MangaModelMangaModel");
                });

            modelBuilder.Entity("MangaModelService.ArtistModel", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"), 1L, 1);

                    b.Property<int?>("AmountOfWork")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArtistBorn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ArtistDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MangaID")
                        .HasColumnType("int");

                    b.Property<string>("NameInNative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiPedia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("mangaModelMangaID")
                        .HasColumnType("int");

                    b.Property<string>("officalWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reddit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistId");

                    b.HasIndex("mangaModelMangaID");

                    b.ToTable("artistModels");
                });

            modelBuilder.Entity("MangaModelService.AssociatedNames", b =>
                {
                    b.Property<int>("AssociatedNamesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssociatedNamesId"), 1L, 1);

                    b.Property<int?>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorID")
                        .HasColumnType("int");

                    b.Property<int?>("MangaID")
                        .HasColumnType("int");

                    b.Property<int?>("VoiceActorId")
                        .HasColumnType("int");

                    b.Property<int?>("mangaModelMangaID")
                        .HasColumnType("int");

                    b.Property<string>("nameString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssociatedNamesId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("AuthorID");

                    b.HasIndex("VoiceActorId");

                    b.HasIndex("mangaModelMangaID");

                    b.ToTable("AssociatedNames");
                });

            modelBuilder.Entity("MangaModelService.AuthorModel", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorID"), 1L, 1);

                    b.Property<int?>("AmountOfWork")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AuthorBorn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuthorDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MangaID")
                        .HasColumnType("int");

                    b.Property<string>("NameInNative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiPedia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("mangaModelMangaID")
                        .HasColumnType("int");

                    b.Property<string>("officalWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reddit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorID");

                    b.HasIndex("mangaModelMangaID");

                    b.ToTable("authorModels");
                });

            modelBuilder.Entity("MangaModelService.BlogModel", b =>
                {
                    b.Property<int>("BlogModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogModelId"), 1L, 1);

                    b.Property<int>("MangaId")
                        .HasColumnType("int");

                    b.Property<string>("UserModelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("mangaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogModelId");

                    b.HasIndex("UserModelId");

                    b.ToTable("blogModels");
                });

            modelBuilder.Entity("MangaModelService.ChapterModel", b =>
                {
                    b.Property<int>("chapterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("chapterID"), 1L, 1);

                    b.Property<int>("GroupScanlatingID")
                        .HasColumnType("int");

                    b.Property<int?>("Volumes")
                        .HasColumnType("int");

                    b.Property<string>("chapterLinkNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chapterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("chapterNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateRelease")
                        .HasColumnType("datetime2");

                    b.HasKey("chapterID");

                    b.ToTable("chapterModels");
                });

            modelBuilder.Entity("MangaModelService.GenresModel", b =>
                {
                    b.Property<int>("GenresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenresId"), 1L, 1);

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MangaID")
                        .HasColumnType("int");

                    b.Property<int?>("TagHeavy")
                        .HasColumnType("int");

                    b.HasKey("GenresId");

                    b.ToTable("GenresModels");
                });

            modelBuilder.Entity("MangaModelService.GroupScanlatingModel", b =>
                {
                    b.Property<int>("GroupScanlatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupScanlatingID"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MasterID")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupScanlatingID");

                    b.ToTable("groupScanlatingModels");

                    b.HasDiscriminator<string>("Discriminator").HasValue("GroupScanlatingModel");
                });

            modelBuilder.Entity("MangaModelService.MangaModel", b =>
                {
                    b.Property<int>("MangaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MangaID"), 1L, 1);

                    b.Property<int>("BlogModelId")
                        .HasColumnType("int");

                    b.Property<string>("CompletelyTranslated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndingYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MangaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MasterID")
                        .HasColumnType("int");

                    b.Property<string>("OfficalLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficialTranslations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalPublisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusInCountryOfOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("futureEvents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("orignalWebtoon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("score")
                        .HasColumnType("float");

                    b.HasKey("MangaID");

                    b.HasIndex("BlogModelId")
                        .IsUnique();

                    b.HasIndex("MasterID")
                        .IsUnique();

                    b.ToTable("mangaModels");
                });

            modelBuilder.Entity("MangaModelService.MasterModel", b =>
                {
                    b.Property<int>("MasterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterID"), 1L, 1);

                    b.Property<int?>("GroupScanlatingID")
                        .HasColumnType("int");

                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterID");

                    b.ToTable("MasterModels");
                });

            modelBuilder.Entity("MangaModelService.PostModel", b =>
                {
                    b.Property<int?>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("PostId"), 1L, 1);

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<int>("BlogModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CommentPostedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("postComment")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<double?>("score")
                        .HasColumnType("float");

                    b.HasKey("PostId");

                    b.HasIndex("BlogModelId");

                    b.HasIndex("UserModelId");

                    b.ToTable("PostModels");
                });

            modelBuilder.Entity("MangaModelService.TagModel", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"), 1L, 1);

                    b.Property<int?>("MangaID")
                        .HasColumnType("int");

                    b.Property<int?>("TagHeavy")
                        .HasColumnType("int");

                    b.Property<string>("TagName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("TagModels");
                });

            modelBuilder.Entity("MangaModelService.VoiceActorModel", b =>
                {
                    b.Property<int>("VoiceActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoiceActorId"), 1L, 1);

                    b.Property<int?>("AmountOfWork")
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MangaID")
                        .HasColumnType("int");

                    b.Property<string>("NameInNative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VoiceBorn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VoiceDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("WikiPedia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("mangaModelMangaID")
                        .HasColumnType("int");

                    b.Property<string>("officalWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reddit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VoiceActorId");

                    b.HasIndex("mangaModelMangaID");

                    b.ToTable("voiceActorModels");
                });

            modelBuilder.Entity("MangaModelTagModel", b =>
                {
                    b.Property<int>("MangaModelsMangaID")
                        .HasColumnType("int");

                    b.Property<int>("TagsModelsTagId")
                        .HasColumnType("int");

                    b.HasKey("MangaModelsMangaID", "TagsModelsTagId");

                    b.HasIndex("TagsModelsTagId");

                    b.ToTable("MangaModelTagModel");
                });

            modelBuilder.Entity("MasterModelUserModel", b =>
                {
                    b.Property<int>("MasterModelMasterID")
                        .HasColumnType("int");

                    b.Property<string>("userModelsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MasterModelMasterID", "userModelsId");

                    b.HasIndex("userModelsId");

                    b.ToTable("MasterModelUserModel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MangaModelService.StudioModel", b =>
                {
                    b.HasBaseType("MangaModelService.GroupScanlatingModel");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DissolutionOfCorporation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudioWebsite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Works")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("StudioModel");
                });

            modelBuilder.Entity("MangaModelService.UserModel", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Allias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForumName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zodiac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("groupScanlationID")
                        .HasColumnType("int");

                    b.Property<int?>("masterId")
                        .HasColumnType("int");

                    b.Property<string>("nameInNativeLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placeOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("postModelID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("UserModel");
                });

            modelBuilder.Entity("ChapterModelGroupScanlatingModel", b =>
                {
                    b.HasOne("MangaModelService.GroupScanlatingModel", null)
                        .WithMany()
                        .HasForeignKey("GroupScanlatingModelsGroupScanlatingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaModelService.ChapterModel", null)
                        .WithMany()
                        .HasForeignKey("chapterModelschapterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenresModelMangaModel", b =>
                {
                    b.HasOne("MangaModelService.GenresModel", null)
                        .WithMany()
                        .HasForeignKey("GenresModelsGenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaModelService.MangaModel", null)
                        .WithMany()
                        .HasForeignKey("MangaModelsMangaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupScanlatingModelMasterModel", b =>
                {
                    b.HasOne("MangaModelService.GroupScanlatingModel", null)
                        .WithMany()
                        .HasForeignKey("GroupScanlatingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaModelService.MasterModel", null)
                        .WithMany()
                        .HasForeignKey("MasterModelsMasterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupScanlatingModelUserModel", b =>
                {
                    b.HasOne("MangaModelService.GroupScanlatingModel", null)
                        .WithMany()
                        .HasForeignKey("GroupScanlatingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaModelService.UserModel", null)
                        .WithMany()
                        .HasForeignKey("userModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MangaModelMangaModel", b =>
                {
                    b.HasOne("MangaModelService.MangaModel", null)
                        .WithMany()
                        .HasForeignKey("RecommendedMangaModelsMangaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaModelService.MangaModel", null)
                        .WithMany()
                        .HasForeignKey("relatedSeriesMangaID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MangaModelService.ArtistModel", b =>
                {
                    b.HasOne("MangaModelService.MangaModel", "mangaModel")
                        .WithMany("ArtistModels")
                        .HasForeignKey("mangaModelMangaID");

                    b.Navigation("mangaModel");
                });

            modelBuilder.Entity("MangaModelService.AssociatedNames", b =>
                {
                    b.HasOne("MangaModelService.ArtistModel", "ArtistModel")
                        .WithMany("AssociatedNames")
                        .HasForeignKey("ArtistId");

                    b.HasOne("MangaModelService.AuthorModel", "AuthorModel")
                        .WithMany("AssociatedNames")
                        .HasForeignKey("AuthorID");

                    b.HasOne("MangaModelService.VoiceActorModel", "VoiceActorModel")
                        .WithMany("AssociatedNames")
                        .HasForeignKey("VoiceActorId");

                    b.HasOne("MangaModelService.MangaModel", "mangaModel")
                        .WithMany("AssociatedNames")
                        .HasForeignKey("mangaModelMangaID");

                    b.Navigation("ArtistModel");

                    b.Navigation("AuthorModel");

                    b.Navigation("VoiceActorModel");

                    b.Navigation("mangaModel");
                });

            modelBuilder.Entity("MangaModelService.AuthorModel", b =>
                {
                    b.HasOne("MangaModelService.MangaModel", "mangaModel")
                        .WithMany("Authormodels")
                        .HasForeignKey("mangaModelMangaID");

                    b.Navigation("mangaModel");
                });

            modelBuilder.Entity("MangaModelService.BlogModel", b =>
                {
                    b.HasOne("MangaModelService.UserModel", null)
                        .WithMany("UserBlogModel")
                        .HasForeignKey("UserModelId");
                });

            modelBuilder.Entity("MangaModelService.MangaModel", b =>
                {
                    b.HasOne("MangaModelService.BlogModel", "BlogModel")
                        .WithOne("MangaModel")
                        .HasForeignKey("MangaModelService.MangaModel", "BlogModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaModelService.MasterModel", "MasterModels")
                        .WithOne("MangaModels")
                        .HasForeignKey("MangaModelService.MangaModel", "MasterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogModel");

                    b.Navigation("MasterModels");
                });

            modelBuilder.Entity("MangaModelService.PostModel", b =>
                {
                    b.HasOne("MangaModelService.BlogModel", "BlogModel")
                        .WithMany("postsModel")
                        .HasForeignKey("BlogModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaModelService.UserModel", "UserModel")
                        .WithMany("PostModel")
                        .HasForeignKey("UserModelId");

                    b.Navigation("BlogModel");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("MangaModelService.VoiceActorModel", b =>
                {
                    b.HasOne("MangaModelService.MangaModel", "mangaModel")
                        .WithMany("VoiceActors")
                        .HasForeignKey("mangaModelMangaID");

                    b.Navigation("mangaModel");
                });

            modelBuilder.Entity("MangaModelTagModel", b =>
                {
                    b.HasOne("MangaModelService.MangaModel", null)
                        .WithMany()
                        .HasForeignKey("MangaModelsMangaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaModelService.TagModel", null)
                        .WithMany()
                        .HasForeignKey("TagsModelsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MasterModelUserModel", b =>
                {
                    b.HasOne("MangaModelService.MasterModel", null)
                        .WithMany()
                        .HasForeignKey("MasterModelMasterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaModelService.UserModel", null)
                        .WithMany()
                        .HasForeignKey("userModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MangaModelService.ArtistModel", b =>
                {
                    b.Navigation("AssociatedNames");
                });

            modelBuilder.Entity("MangaModelService.AuthorModel", b =>
                {
                    b.Navigation("AssociatedNames");
                });

            modelBuilder.Entity("MangaModelService.BlogModel", b =>
                {
                    b.Navigation("MangaModel")
                        .IsRequired();

                    b.Navigation("postsModel");
                });

            modelBuilder.Entity("MangaModelService.MangaModel", b =>
                {
                    b.Navigation("ArtistModels");

                    b.Navigation("AssociatedNames");

                    b.Navigation("Authormodels");

                    b.Navigation("VoiceActors");
                });

            modelBuilder.Entity("MangaModelService.MasterModel", b =>
                {
                    b.Navigation("MangaModels")
                        .IsRequired();
                });

            modelBuilder.Entity("MangaModelService.VoiceActorModel", b =>
                {
                    b.Navigation("AssociatedNames");
                });

            modelBuilder.Entity("MangaModelService.UserModel", b =>
                {
                    b.Navigation("PostModel");

                    b.Navigation("UserBlogModel");
                });
#pragma warning restore 612, 618
        }
    }
}
